
package Odev_2;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
* @file Jframe
* @description Tasarım işlemleri bu sınıfta oluşturulmuştur. Ayrıca buton,listeleme gibi  işlemleride buradan yürütülmektedir.
* @assignment 2.
* @date 19.12.2019 / 22.12.2019
* @author Omer Faruk Dursun / omerfaruk.dursun@stu.fsm.edu.tr
*/


public class NewJFrame extends javax.swing.JFrame {

    Queue q=new Queue(); // Kuyruk oluşyuruyoruz
    Queue cikan=new Queue();
    
    DefaultListModel<String> dlm=new DefaultListModel<>(); // Verileri yazdırığımız yerler.
    DefaultListModel<String> dlm2=new DefaultListModel<>();
    DefaultListModel<String> dlm3=new DefaultListModel<>();
    public NewJFrame() {
        initComponents();
        lstMusteriler.setModel(dlm);
        lstDequeue.setModel(dlm2);
        lstSonuc.setModel(dlm3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMusteriler = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnDequeue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDequeue = new javax.swing.JList<>();
        btnToplamSure = new javax.swing.JButton();
        btnToplamFatura = new javax.swing.JButton();
        btnOcelikGir = new javax.swing.JButton();
        txtOncelik = new javax.swing.JTextField();
        btnOTSure = new javax.swing.JButton();
        txtOTSure = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSonuc = new javax.swing.JList<>();
        btnFaturaGir = new javax.swing.JButton();
        txtFaturaGir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOku.setText("Dosya Oku");
        btnOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkuActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstMusteriler);

        jLabel1.setText("Müşteriler Listesi");

        btnDequeue.setText("Müşteri Çağır");
        btnDequeue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDequeueActionPerformed(evt);
            }
        });

        jLabel2.setText("Kuyruktan Çıkan Müşteriler");

        jScrollPane2.setViewportView(lstDequeue);

        btnToplamSure.setText("Toplam Süre");
        btnToplamSure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplamSureActionPerformed(evt);
            }
        });

        btnToplamFatura.setText("Toplam Fatura");
        btnToplamFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplamFaturaActionPerformed(evt);
            }
        });

        btnOcelikGir.setText("Öncelik Gir");
        btnOcelikGir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcelikGirActionPerformed(evt);
            }
        });

        btnOTSure.setText("Oncelik Toplam Süre");
        btnOTSure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOTSureActionPerformed(evt);
            }
        });

        jLabel3.setText("Sonuç");

        jScrollPane3.setViewportView(lstSonuc);

        btnFaturaGir.setText("Fatura Gir");
        btnFaturaGir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturaGirActionPerformed(evt);
            }
        });

        txtFaturaGir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaturaGirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOku)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDequeue)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOcelikGir)
                                .addGap(28, 28, 28)
                                .addComponent(txtOncelik, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnToplamSure)
                                .addGap(30, 30, 30)
                                .addComponent(btnToplamFatura))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOTSure)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtOTSure, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFaturaGir, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(btnFaturaGir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOku)
                    .addComponent(btnDequeue)
                    .addComponent(btnToplamSure)
                    .addComponent(btnToplamFatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnOcelikGir)
                    .addComponent(txtOncelik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOTSure)
                            .addComponent(txtOTSure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnFaturaGir)
                                .addGap(18, 18, 18)
                                .addComponent(txtFaturaGir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkuActionPerformed
        try {
            File f=null; // bu kısımda verinin yolunu belirtip dosyayı okumak için kullanıyoruz
            String path=null;
            JFileChooser fileChooser=new JFileChooser();
            fileChooser.showOpenDialog(fileChooser);
            f=fileChooser.getSelectedFile();
            path=f.getAbsolutePath();
            q.dosyaOku(path);
            Node temp = q.front;
            while (temp != null) {
                dlm.addElement(temp.toString());
                temp = temp.next;
            }  
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnOkuActionPerformed

    private void txtFaturaGirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaturaGirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaturaGirActionPerformed

    private void btnDequeueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDequeueActionPerformed
        cikan.enqueue(q.nDequeue());
        dlm.clear();
        Node temp = q.front;
            while (temp != null) {
                dlm.addElement(temp.toString());
                temp = temp.next;
            }  
            dlm2.clear();
            Node temp2 = cikan.front;
            while (temp2 != null) {
                dlm2.addElement(temp2.toString());
                temp2 = temp2.next;
            }  
        
    }//GEN-LAST:event_btnDequeueActionPerformed

    private void btnToplamSureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplamSureActionPerformed
        dlm3.clear();
        dlm3.addElement("Toplam Süre: "+cikan.toplamSure()); // Toplam Süreyi yazdırma.
    }//GEN-LAST:event_btnToplamSureActionPerformed

    private void btnToplamFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplamFaturaActionPerformed
        dlm3.clear();
        dlm3.addElement("Toplam Fatura: "+cikan.toplamFatura()); //Toplam Süreyi Yazdırma
    }//GEN-LAST:event_btnToplamFaturaActionPerformed

    private void btnOcelikGirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcelikGirActionPerformed
        dlm3.clear();
        int oncelik=0;
        try {
              oncelik=Integer.valueOf(txtOncelik.getText()); // Önceliği alıyor
        } catch (Exception e) {
        }
        int counter=1;
        Node temp=cikan.front;
         while (temp != null) { // Bu önceliğe sahip elemanları yazdırıyor.
             if (temp.oncelik==oncelik) {
                dlm3.addElement(counter+". Sırada - "+temp.AdSoyad);
             }
                counter++;
                temp = temp.next;
            }  
        
    }//GEN-LAST:event_btnOcelikGirActionPerformed

    private void btnOTSureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOTSureActionPerformed
        dlm3.clear();
       int oncelik=0;
        try {
              oncelik=Integer.valueOf(txtOTSure.getText()); //Önceliği alıyor
        } catch (Exception e) {
        }
        int toplam=0;
        Node temp=cikan.front;
         while (temp != null) { // İstediği önceliği yazdırıyor.
             if (temp.oncelik==oncelik) {
                toplam+=temp.zaman;
             }
                
                temp = temp.next;
        }  
       dlm3.addElement(oncelik+" Nolu Öncelikte Toplam Süre : "+toplam);
             
    }//GEN-LAST:event_btnOTSureActionPerformed

    private void btnFaturaGirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturaGirActionPerformed
        dlm3.clear();
        String fatura=txtFaturaGir.getText(); //Faturanın adını alıyor
        Node temp=cikan.front;
         while (temp != null) {
             if (temp.FaturaTipi.equals(fatura)) { //İstenilen Faturaya ait elemanları yazdırıyor.
                dlm3.addElement(temp.toString());
             }
                temp = temp.next;
            }  
    }//GEN-LAST:event_btnFaturaGirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDequeue;
    private javax.swing.JButton btnFaturaGir;
    private javax.swing.JButton btnOTSure;
    private javax.swing.JButton btnOcelikGir;
    private javax.swing.JButton btnOku;
    private javax.swing.JButton btnToplamFatura;
    private javax.swing.JButton btnToplamSure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstDequeue;
    private javax.swing.JList<String> lstMusteriler;
    private javax.swing.JList<String> lstSonuc;
    private javax.swing.JTextField txtFaturaGir;
    private javax.swing.JTextField txtOTSure;
    private javax.swing.JTextField txtOncelik;
    // End of variables declaration//GEN-END:variables
}
